package it.comune.trieste.ouf.semantic.application;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.Duration;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class GovernanceService {
  private final JdbcClient db;private final ObjectMapper json;
  public GovernanceService(JdbcClient db,ObjectMapper json){this.db=db;this.json=json;}
  private static void human(String type){if(!"HUMAN".equals(type))throw new Forbidden("HUMAN_IDENTITY_REQUIRED");}

  @Transactional public Map<String,Object> challenge(UUID revision,String hash,Duration ttl,String actor,String type,String correlation){UUID id=UUID.randomUUID();int n=db.sql("update ouf_sem.artifact_revision set lifecycle_status='UNDER_REVIEW',content_hash=:h where revision_id=:r and lifecycle_status='DRAFT'").param("h",hash).param("r",revision).update();if(n!=1)throw new Conflict("REVISION_NOT_DRAFT");db.sql("insert into ouf_sem.approval_challenge(challenge_id,revision_id,target_content_hash,status,expires_at,created_by_subject) values(:i,:r,:h,'OPEN',transaction_timestamp()+cast(:ttl as interval),:a)").param("i",id).param("r",revision).param("h",hash).param("ttl",ttl.toSeconds()+" seconds").param("a",actor).update();audit("SEMANTIC_APPROVAL_CHALLENGE_CREATED",actor,type,"APPROVAL_CHALLENGE",id.toString(),correlation,Map.of("revisionId",revision,"contentHash",hash));Map<String,Object> out=new LinkedHashMap<>(card(id));out.put("challengeId",id);out.put("revisionId",revision);out.put("targetContentHash",hash);out.put("trustedApprovalRef","ths://semantic-approval-challenges/"+id);return out;}
  @Transactional public Map<String,Object> decide(UUID challenge,String decision,String actor,String type,String authorizationDecisionRef,String correlation){human(type);if(!Set.of("APPROVED","REJECTED").contains(decision))throw new IllegalArgumentException("APPROVAL_DECISION_INVALID");UUID id=UUID.randomUUID();Map<String,Object> row=db.sql("select revision_id,target_content_hash from ouf_sem.approval_challenge where challenge_id=:i and status='OPEN' and expires_at>transaction_timestamp() for update").param("i",challenge).query().listOfRows().stream().findFirst().orElseThrow(()->new Conflict("APPROVAL_CHALLENGE_NOT_OPEN"));db.sql("insert into ouf_sem.approval_decision(decision_id,challenge_id,decision,target_content_hash,decided_by_subject,actor_type,authorization_context_ref) values(:i,:c,:d,:h,:a,:t,:x)").param("i",id).param("c",challenge).param("d",decision).param("h",row.get("target_content_hash")).param("a",actor).param("t",type).param("x",authorizationDecisionRef).update();db.sql("update ouf_sem.approval_challenge set status=:d where challenge_id=:c").param("d",decision).param("c",challenge).update();if("REJECTED".equals(decision))db.sql("update ouf_sem.artifact_revision set lifecycle_status='DRAFT',row_version=row_version+1 where revision_id=:r and lifecycle_status='UNDER_REVIEW'").param("r",row.get("revision_id")).update();audit("SEMANTIC_"+decision,actor,type,"APPROVAL_CHALLENGE",challenge.toString(),correlation,Map.of("decisionId",id,"revisionId",row.get("revision_id"),"contentHash",row.get("target_content_hash"),"authorizationDecisionRef",authorizationDecisionRef));return Map.of("decisionId",id,"challengeId",challenge,"decision",decision);}
  @Transactional public Map<String,Object> publish(UUID revision,UUID decision,String key,String hash,String actor,String type,String correlation){human(type);UUID set=db.sql("select ouf_sem.publish_revision(:r,:d,:k,:h,:a,:c)").param("r",revision).param("d",decision).param("k",key).param("h",hash).param("a",actor).param("c",correlation).query(UUID.class).single();String manifest=db.sql("select checksum from ouf_sem.semantic_publication_set where publication_set_id=:s").param("s",set).query(String.class).single();return Map.of("publicationSetId",set,"status","PUBLISHED","manifestHash",manifest);}
  @Transactional public Map<String,Object> lifecycle(UUID revision,String target,String actor,String type,String authorizationDecisionRef,String correlation){human(type);String state=db.sql("select ouf_sem.govern_revision_lifecycle(:r,:s,:a,:x,:c)").param("r",revision).param("s",target).param("a",actor).param("x",authorizationDecisionRef).param("c",correlation).query(String.class).single();return Map.of("revisionId",revision,"status",state);}
  public UUID retiredRevision(UUID artifact){return db.sql("select revision_id from ouf_sem.artifact_revision where artifact_id=:a and lifecycle_status='DEPRECATED' order by revision_no desc limit 1").param("a",artifact).query(UUID.class).list().stream().findFirst().orElseThrow(()->new Conflict("DEPRECATED_REVISION_NOT_FOUND"));}
  public Map<String,Object> card(UUID challenge){Map<String,Object> row=db.sql("select c.challenge_id,c.revision_id,c.target_content_hash,c.status,c.expires_at,c.created_at,a.artifact_id,a.semantic_id,a.artifact_type,a.namespace,a.local_name,a.owner_ref,a.authority_ref,r.revision_no,r.semantic_version,r.row_version,r.label_json::text label_json,r.description_json::text description_json,r.definition_json::text definition_json from ouf_sem.approval_challenge c join ouf_sem.artifact_revision r on r.revision_id=c.revision_id join ouf_sem.semantic_artifact a on a.artifact_id=r.artifact_id where c.challenge_id=:i").param("i",challenge).query().listOfRows().stream().findFirst().orElseThrow(()->new NoSuchElementException("APPROVAL_CHALLENGE_NOT_FOUND"));Map<String,Object> out=new LinkedHashMap<>(row);for(String field:List.of("label_json","description_json","definition_json"))try{out.put(field,json.readValue(String.valueOf(row.get(field)),Object.class));}catch(Exception e){throw new IllegalStateException("SEMANTIC_CARD_DECODE_FAILED",e);}out.put("trustedApprovalRef","ths://semantic-approval-challenges/"+challenge);out.put("humanAuthorityRequired",true);return out;}
  private void audit(String event,String actor,String type,String resourceType,String resourceId,String correlation,Object detail){try{Map<String,Object> payload=new LinkedHashMap<>();payload.put("actorType",type);payload.put("detail",detail);db.sql("insert into ouf_sem.audit_event(event_id,event_type,subject_ref,resource_type,resource_id,correlation_id,detail_json) values(:i,:e,:a,:t,:r,:c,cast(:d as jsonb))").param("i",UUID.randomUUID()).param("e",event).param("a",actor).param("t",resourceType).param("r",resourceId).param("c",correlation).param("d",json.writeValueAsString(payload)).update();}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalStateException(e);}}
  public static class Forbidden extends RuntimeException{public Forbidden(String m){super(m);}}
  public static class Conflict extends RuntimeException{public Conflict(String m){super(m);}}
}
