package it.comune.trieste.ouf.semantic.application;

import com.fasterxml.jackson.databind.*;
import it.comune.trieste.ouf.semantic.domain.*;
import java.util.*;
import org.apache.jena.rdf.model.Model;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class InterchangeService {
  private final JdbcClient db;private final SafeRdfParser parser;private final RdfInterchangeCodec codec;private final ObjectMapper json;
  public InterchangeService(JdbcClient db,SafeRdfParser parser,RdfInterchangeCodec codec,ObjectMapper json){this.db=db;this.parser=parser;this.codec=codec;this.json=json;}
  @Transactional public Map<String,Object> importDraft(String semanticId,String type,String namespace,String localName,String owner,String authority,String version,String mediaType,byte[] bytes,String actor){var parsed=parser.parse(bytes,mediaType);codec.validateImportedIdentity(codec.parse(bytes,mediaType),semanticId,type);UUID artifact=UUID.randomUUID(),revision=UUID.randomUUID();db.sql("insert into ouf_sem.semantic_artifact(artifact_id,semantic_id,artifact_type,namespace,local_name,owner_ref,authority_ref,origin_kind) values(:a,:s,:t,:n,:l,:o,:u,'IMPORTED')").param("a",artifact).param("s",semanticId).param("t",type).param("n",namespace).param("l",localName).param("o",owner).param("u",authority).update();db.sql("insert into ouf_sem.artifact_revision(revision_id,artifact_id,revision_no,lifecycle_status,semantic_version,created_by_subject) values(:r,:a,1,'DRAFT',:v,:x)").param("r",revision).param("a",artifact).param("v",version).param("x",actor).update();db.sql("insert into ouf_sem.revision_interchange_snapshot values(:r,:m,:h,:b,:c,:a,transaction_timestamp())").param("r",revision).param("m",mediaType).param("h",parsed.contentHash()).param("b",bytes).param("c",parsed.statementCount()).param("a",actor).update();return Map.of("artifactId",artifact,"revisionId",revision,"semanticId",semanticId,"status","DRAFT","contentHash",parsed.contentHash(),"statementCount",parsed.statementCount());}
  public Representation export(UUID publicationSet,UUID artifact,String accept){Map<String,Object> row=db.sql("select a.semantic_id,a.artifact_id,a.artifact_type,a.namespace,a.local_name,r.revision_id,r.semantic_version,r.lifecycle_status status,r.label_json,r.description_json,r.definition_json,s.media_type,s.content_bytes from ouf_sem.semantic_publication_member m join ouf_sem.artifact_revision r on r.revision_id=m.revision_id join ouf_sem.semantic_artifact a on a.artifact_id=r.artifact_id left join ouf_sem.revision_interchange_snapshot s on s.revision_id=r.revision_id where m.publication_set_id=:p and a.artifact_id=:a").param("p",publicationSet).param("a",artifact).query().singleRow();String type=row.get("artifact_type").toString();JsonNode labels=tree(row.get("label_json")),descriptions=tree(row.get("description_json")),definition=tree(row.get("definition_json"));if("application/json".equals(accept)){try{return new Representation(json.writeValueAsBytes(row),accept);}catch(Exception e){throw new IllegalStateException("JSON_EXPORT_FAILED",e);}}if("text/csv".equals(accept)){if(!"VOCABULARY".equals(type)&&!"CONCEPT".equals(type))throw new IllegalArgumentException("CSV_ONLY_FOR_VOCABULARY");return new Representation(codec.vocabularyCsv(row.get("semantic_id").toString(),labels,definition),accept);}Model model=row.get("content_bytes") instanceof byte[] bytes?codec.parse(bytes,row.get("media_type").toString()):codec.nativeView(row.get("semantic_id").toString(),type,labels,descriptions,definition);return new Representation(codec.serialize(model,accept),accept);}
  private JsonNode tree(Object value){if(value instanceof JsonNode n)return n;try{return json.readTree(value==null?"{}":value.toString());}catch(Exception e){throw new IllegalStateException("STORED_JSON_INVALID",e);}}
  public record Representation(byte[] body,String mediaType){}
}
