package it.comune.trieste.ouf.semantic.application;

import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ValidationService {
  private final JdbcClient db;
  public ValidationService(JdbcClient db){this.db=db;}
  @Transactional public Map<String,Object> validate(UUID revision,String actor){UUID run=db.sql("select ouf_sem.validate_revision(:r,:a)").param("r",revision).param("a",actor).query(UUID.class).single();return validation(run);}
  public Map<String,Object> validation(UUID run){Map<String,Object> header=db.sql("select validation_run_id,revision_id,status,error_count,warning_count,validated_row_version,validated_content_hash,validator_version,created_by_subject,created_at from ouf_sem.validation_run where validation_run_id=:i").param("i",run).query().singleRow();List<Map<String,Object>> issues=db.sql("select level,rule_id,severity,path,message,details_json from ouf_sem.validation_issue where validation_run_id=:i order by severity,rule_id,path").param("i",run).query().listOfRows();Map<String,Object> out=new LinkedHashMap<>(header);out.put("issues",issues);return out;}
  @Transactional public Map<String,Object> impact(UUID from,UUID to,String actor){UUID id=db.sql("select ouf_sem.compute_impact(:f,:t,:a)").param("f",from).param("t",to).param("a",actor).query(UUID.class).single();return impact(id);}
  public Map<String,Object> impact(UUID id){return db.sql("select i.change_id,a.semantic_id artifact,i.from_revision_id,i.to_revision_id,i.computed_classification classification,i.approved_classification,i.impacts_json impacts,i.blocking_issues,i.migration_proposal_id,i.created_at from ouf_sem.impact_report i join ouf_sem.semantic_artifact a using(artifact_id) where i.change_id=:i").param("i",id).query().singleRow();}
  public Map<String,Object> resolve(String semanticId,UUID revision,UUID publicationSet){List<Map<String,Object>> rows=db.sql("select a.semantic_id,a.artifact_id,r.revision_id,a.artifact_type,r.semantic_version,r.lifecycle_status status,coalesce(o.canonical_uri,a.semantic_id) canonical_uri,a.namespace,a.local_name,r.label_json label,m.publication_set_id from ouf_sem.semantic_publication_member m join ouf_sem.artifact_revision r on r.revision_id=m.revision_id join ouf_sem.semantic_artifact a on a.artifact_id=r.artifact_id left join lateral (select canonical_uri from ouf_sem.external_semantic_origin x where x.artifact_id=a.artifact_id order by canonical_uri limit 1) o on true where m.publication_set_id=:p and m.revision_id=:r and m.semantic_id=:s").param("p",publicationSet).param("r",revision).param("s",semanticId).query().listOfRows();if(rows.size()!=1)throw new NoSuchElementException("SEMANTIC_REFERENCE_NOT_FOUND");return rows.get(0);}
  @Transactional public void registerConsumer(String consumerType,String consumerId,String semanticId,UUID revision,UUID publicationSet){long member=db.sql("select count(*) from ouf_sem.semantic_publication_member where publication_set_id=:p and revision_id=:r and semantic_id=:s").param("p",publicationSet).param("r",revision).param("s",semanticId).query(Long.class).single();if(member!=1)throw new IllegalArgumentException("SEMANTIC_REFERENCE_NOT_FOUND");db.sql("insert into ouf_sem.semantic_consumer_reference(consumer_type,consumer_id,semantic_id,revision_id,publication_set_id) values(:t,:c,:s,:r,:p) on conflict(consumer_type,consumer_id,semantic_id) do update set revision_id=excluded.revision_id,publication_set_id=excluded.publication_set_id,registered_at=transaction_timestamp()").param("t",consumerType).param("c",consumerId).param("s",semanticId).param("r",revision).param("p",publicationSet).update();}
}
