"""Deterministic isolated source closure; deployment pins generated bytes."""
import hashlib
from pathlib import Path
MODULES=('verify_semantic_image_archive','prepare_semantic_image_sbom')
def build(root):
    sources={name:(root/(name+'.py')).read_text() for name in MODULES}
    return '"""Generated offline image SBOM preparer; no authority grant."""\nimport sys,types\nSOURCE_HASHES='+repr({k:hashlib.sha256(v.encode()).hexdigest() for k,v in sources.items()})+'\nSOURCES='+repr(sources)+'''\npackage=types.ModuleType('tools');package.__path__=[];sys.modules['tools']=package
for name,source in SOURCES.items():
    module=types.ModuleType('tools.'+name);module.__package__='tools';module.__file__='<ouf-image-sbom-source-closure>'
    sys.modules[module.__name__]=module;setattr(package,name,module)
    exec(compile(source,module.__file__,'exec'),module.__dict__)
if __name__=='__main__':raise SystemExit(sys.modules['tools.prepare_semantic_image_sbom'].main())
'''
if __name__=='__main__':
    import argparse
    p=argparse.ArgumentParser();p.add_argument('--output',required=True,type=Path);a=p.parse_args()
    a.output.write_text(build(Path(__file__).parent))
